name: Build résumé and cv

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache Résumé
      - name: Cache résumé
        id: cache-resume
        uses: actions/cache@v3
        with:
          path: ./resume.pdf
          key: resume-${{ hashFiles('./resume') }}

      # Build résumé
      - name: Build source (latex)
        if: steps.cache-resume.outputs.cache-hit != 'true'
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./resume.tex

      # Replace latest if push to main
      - name: Delete latest release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Replace latest release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Résumé
          body: "The latest official résumé of Spencer C. Imbleau."
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            resume.pdf
