name: latex-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache PDF
      - name: PDF Cache
        id: cache-pdf
        uses: actions/cache@v3
        with:
          path: ./aux/resume.pdf
          key: resume-${{ hashFiles('./src') }}

      # Build resume
      - name: Build source (latex)
        if: steps.cache-pdf.outputs.cache-hit != 'true'
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          root_file: ./src/resume.tex

      # Replace latest if push to main
      # TODO : Replace source.tar.gz, source.zip
      - name: Replace latest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: latest
          name: Résumé
          files: |
            resume.pdf
