name: latex-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build latex
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          root_file: resume.tex

      - name: release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: latest
          name: Résumé
          files: resume.pdf
