name: latex-build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build latex
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          root_file: |
            resume.tex

      - name: upload resume
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v3
        with:
          path: resume.pdf
