name: Release résumé and cirriculum vitae

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache résumé
      - name: Cache resume
        id: cache-resume
        uses: actions/cache@v3
        with:
          path: ./resume.pdf
          key: resume-${{ hashFiles('./resume') }}

      # Build résumé
      - name: Build source (latex)
        if: steps.cache-resume.outputs.cache-hit != 'true'
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./resume.tex

      # Upload PDF
      - name: Upload résumé PDF
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            resume.pdf
