name: release

on:
  release:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Cache Résumé
      - name: Cache résumé
        id: cache-resume
        uses: actions/cache@v3
        with:
          path: ./resume.pdf
          key: resume-${{ hashFiles('./resume') }}

      # Build résumé
      - name: Build résumé (latex)
        if: steps.cache-resume.outputs.cache-hit != 'true'
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_shell_escape: true
          latexmk_use_xelatex: true
          root_file: ./resume.tex

      # Cache CV
      - name: Cache CV
        id: cache-cv
        uses: actions/cache@v3
        with:
          path: ./cv.pdf
          key: cv-${{ hashFiles('./cv') }}

      # Upload PDFs
      - name: Upload PDFs
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            resume.pdf
            cv.pdf
